### PR TITLE
Added error messages 

### PR DESCRIPTION
**Pull request by AQMpolyface**
added error messages where there was a "// Handle error" without error handling

### CODE REVIEW

**Review by mirarr-app — CHANGES_REQUESTED** [review]
Thank you but please don't include pubspec.yaml and pubspec.lock when pushing the code and send it again.

**Comment by AQMpolyface** [comment]
i have removed the files you indicated. Please let me know if there's anything else that needs adjustment.

**Comment by mirarr-app** [comment]
@AQMpolyface thanks. But now there's some dotfiles probably from your ide. Just commit the lib folder.

**Review by mirarr-app — APPROVED** [review]

**Review by mirarr-app — CHANGES_REQUESTED** [review]
Please only commit lib directory.

**Comment by AQMpolyface** [comment]
Apologies for the confusion earlier, I believe I’ve done a clean fork this time with only the lib included. Would it be okay to submit a new pull request? I’m really sorry for the inconvenience.

**Comment by AQMpolyface** [comment]
I would understand if you dont want me to do it tho, i just made a mess for like 5 more error handling. Sorry.

**Comment by mirarr-app** [comment]
@AQMpolyface of course it's ok. Don't worry about it.
You can always run git show HEAD~n . N being number of commits you made to see what you changed before pushing. Let me know if you need help

**Pull request closed without merging**
