### PR TITLE
proxied requests

### PR DESCRIPTION
**Pull request by parsamrrelax**

### CODE REVIEW

**Comment by PanZWarzywniaka** [comment]
Hi, I looked at the commit on proxied requests and it seems like now app is dependant on this one blog domain https://maybeparsa.top/, meaning it's very brittle.

Shouldn't the default request be to [TMDB](https://api.themoviedb.org) directly and use the proxied version as a fallback?

**Comment by mirarr-app** [comment]
Hi @PanZWarzywniaka, you're absolutely correct. It didn't come to my mind to use it as a fallback. Will implement it in the next update. 
(That's my personal blog btw and I used it since the default cloudflare worker domain is also blocked in some countries and it has a daily request limit.)

**Comment by PanZWarzywniaka** [comment]
Sounds good!
I am not sure how cloudlare workers pricing work but I guess the less proxies you handle the better for your account as well!

**Comment by mirarr-app** [comment]
Upon further considering I've decided not to revert back to the default tmdb urls because the performance has improved greatly and there is a lot of caching which I like. I will add an option in settings to revert back to original urls or vice versa (use the proxied version).

**Pull request merged**
